### PR TITLE
UPD UI

### PR DESCRIPTION
**Pull request by VladimirChubenko**
Update styles + new page (committees)

### CODE REVIEW

**Comment by thehapax** [comment]
Hi @VladimirChubenko, Leo asked me to review your PR. There appear to be missing files, can you please amend and update, thanks. 

[2020-06-15 07:33:28] ERROR `/fonts/franklin-ghotic/stylesheet.css' not found.
[2020-06-15 07:33:54] ERROR `/fonts/franklin-ghotic/stylesheet.css' not found.
[2020-06-15 07:33:54] ERROR `/styles/ajax-loader.gif' not found.
[2020-06-15 07:33:54] ERROR `/styles/fonts/slick.woff' not found.
[2020-06-15 07:33:54] ERROR `/styles/fonts/slick.ttf' not found.

**Comment by VladimirChubenko** [comment]
fix fonts errors

**Comment by thehapax** [comment]
@Liongrass ok to merge.

**Comment by Liongrass** [comment]
Thank you for your great work @VladimirChubenko!
And thank you especially @thehapax for your help reviewing this!

**Pull request merged**
